name: moviedb_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+4

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  animated_theme_switcher: ^2.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.0
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  lazy_load_scrollview: ^1.3.0
  palette_generator: ^0.3.3+2
  photo_view: ^0.14.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/logo.svg

  fonts:
    - family: muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
        - asset: assets/fonts/Muli-Regular.ttf
        - asset: assets/fonts/Muli-SemiBold.ttf
  
